version: '3'

services:
  redisV2:
    image: redis:latest
    hostname: redisV2
    restart: always
    command: ["redis-server"]
    ports:
      - '6379:6379'
    volumes:
      - "./redis:/data"
  redisV3:
    image: redis:latest
    hostname: redisV3
    restart: always
    command: ["redis-server"]
    ports:
      - '6378:6379'
    volumes:
      - "./redis2:/data"
  postgresV2:
    image: postgres:16.0-alpine
    hostname: postgresV2
    shm_size: 4g
    ports: [ 5433:5432 ]
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - "./postgres:/var/lib/postgresql/data:rw"