name: Cardano Dex Index Docker Build

on:
  push:
    branches: ["master"]

jobs:
  cardano-db-writer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./modules/db-writer/sys/Dockerfile
          tags: clarkteddyswap/cardano-db-writer:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: git_commit_id=${{ github.sha }}
          platforms: linux/amd64
  cardano-rates-resolver:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./modules/rates-resolver/sys/Dockerfile
          tags: clarkteddyswap/cardano-rates-resolver:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: git_commit_id=${{ github.sha }}
          platforms: linux/amd64
  cardano-markets-api:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./modules/markets-api/sys/Dockerfile
          tags: clarkteddyswap/markets-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: git_commit_id=${{ github.sha }}
          platforms: linux/amd64